#!/bin/bash
COOKIE=$(jq -r '.xhs.cookie' config.json)
X_S=$(jq -r '.xhs."x-s"' config.json)
X_S_COMMON=$(jq -r '.xhs."x-s-common"' config.json)
X_T=$(jq -r '.xhs."x-t"' config.json)
X_B3_TRACEID=$(jq -r '.xhs."x-b3-traceid"' config.json)

curl -s 'https://edith.xiaohongshu.com/api/sns/web/v1/search/notes' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'content-type: application/json;charset=UTF-8' \
  -b "$COOKIE" \
  -H 'origin: https://www.xiaohongshu.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://www.xiaohongshu.com/' \
  -H 'sec-ch-ua: "Microsoft Edge";v="143", "Chromium";v="143", "Not A(Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0' \
  -H "x-b3-traceid: $X_B3_TRACEID" \
  -H "x-s: $X_S" \
  -H "x-s-common: $X_S_COMMON" \
  -H "x-t: $X_T" \
  -H 'x-xray-traceid: cd86bdadbc350a01115e077a1d94b130' \
  --data-raw '{"keyword":"java社招面试","page":1,"page_size":20,"search_id":"2fpf1bbpsu0mkatu1lon1","sort":"general","note_type":0,"ext_flags":[],"filters":[{"tags":["general"],"type":"sort_type"},{"tags":["不限"],"type":"filter_note_type"},{"tags":["不限"],"type":"filter_note_time"},{"tags":["不限"],"type":"filter_note_range"},{"tags":["不限"],"type":"filter_pos_distance"}],"geo":"","image_formats":["jpg","webp","avif"]}'


